Ft login page
atlp-rwanda/Dominators-Phantom-FE pull request #10
Opened 2022-04-18 08:38 UTC by GilbertUp

2022-04-18 09:22 UTC, fab-ryan requested changes
no login page

2022-04-18 10:55 UTC, fab-ryan approved these changes

2022-04-26 15:39 UTC, aimelive approved these changes

2022-04-28 14:27 UTC, furebo requested changes
Please rebase from develop and resolve the conflict and remember to squash the commits

2022-05-09 10:11 UTC, furebo requested changes

2022-05-09 10:11 UTC, furebo commented on src/components/login/LoginComponent.js
> +    .then((res)=>{
put the backend url in environment variable and include it here, because this will not work in production.

2022-05-09 10:11 UTC, furebo commented on src/pages/Logout.jsx
> +// import logout from '../images/logout.png'
Please remove these comments

2022-05-10 13:47 UTC, furebo requested changes

2022-05-10 13:47 UTC, furebo commented on src/components/login/LoginComponent.js
> +   redirect("/dashboard")
The value of token in localStorage must be the token from the backend response. Please remove the hardcoded token.

2022-05-14 06:12 UTC, furebo approved these changes

2022-05-14 06:12 UTC, merged