Ft logout page
atlp-rwanda/Dominators-Phantom-FE pull request #11
Opened 2022-04-18 10:58 UTC by gerard1001

2022-04-18 11:08 UTC, gerard1001 commented
Logout page

2022-04-20 15:31 UTC, fab-ryan approved these changes

2022-05-13 17:26 UTC, UmuhireJessie approved these changes

2022-05-19 17:45 UTC, Anguandia commented
@gerard1001 , please give the PR a meaningful description as illustrated in the best practice doc and rebase

2022-05-20 10:33 UTC, furebo requested changes

2022-05-20 10:33 UTC, furebo commented on src/components/Logout/Logout.js
> +            </div>
Please add event to the logout

2022-06-09 12:01 UTC, aimelive approved these changes

2022-06-09 12:08 UTC, GilbertUp approved these changes

2022-06-14 20:39 UTC, Anguandia commented
This has already been implemented with login

2022-06-14 20:39 UTC, closed without merging