Ft landing page
atlp-rwanda/Dominators-Phantom-FE pull request #14
Opened 2022-04-20 15:46 UTC by fab-ryan

Final ft landing page and Skeleton Ui in landing Page

2022-04-20 17:21 UTC, Anguandia requested changes
Also work on :
- Your PR description
- Squash your commits into 1

2022-04-20 17:21 UTC, Anguandia commented on src/components/Headers/header.css
> +    margin-top: 70px;
The margin is too big please reduce

2022-04-22 17:42 UTC, aimelive approved these changes

2022-04-22 17:58 UTC, GilbertUp approved these changes

2022-05-03 13:37 UTC, furebo approved these changes

2022-05-03 13:38 UTC, merged