register driver and operators design
atlp-rwanda/Dominators-Phantom-FE pull request #18
Opened 2022-04-29 12:32 UTC by UmuhireJessie

make suggestions on the design

2022-05-03 09:40 UTC, fab-ryan approved these changes

2022-05-03 11:00 UTC, aimelive approved these changes

2022-05-14 06:32 UTC, GilbertUp approved these changes

2022-05-14 06:33 UTC, GilbertUp approved these changes
resolve conflicts!

2022-06-12 20:02 UTC, Anguandia commented
@UmuhireJessie , please get in touch with @furebo to resolve these conflicts, then squash your commits

2022-06-13 18:42 UTC, furebo requested changes

2022-06-13 18:42 UTC, furebo commented on src/components/admin-header/Header.css
> +=======
Please resolve these conflicts

2022-06-13 18:42 UTC, furebo commented on src/components/admin-sidebar/SideBar.js
> +<<<<<<< HEAD
Remove the conflicts also in this file

2022-06-13 18:42 UTC, furebo commented on webpack.prod.js
> +<<<<<<< HEAD
the same here remove the conflicts

2022-06-13 18:42 UTC, furebo commented on webpack.prod.js
> +<<<<<<< HEAD
Remove conflicts in this file

2022-06-13 18:42 UTC, furebo commented on webpack.dev.js
> +<<<<<<< HEAD
Please remove conflicts

2022-06-13 22:25 UTC, tjeaneric commented on src/components/admin-header/Header.css
> +=======
Resolved now.

2022-06-13 22:25 UTC, tjeaneric commented on src/components/admin-sidebar/SideBar.js
> +<<<<<<< HEAD
Resolved now.

2022-06-13 22:25 UTC, tjeaneric commented on webpack.prod.js
> +<<<<<<< HEAD
Resolved now.

2022-06-13 22:25 UTC, tjeaneric commented on webpack.prod.js
> +<<<<<<< HEAD
Resolved now.

2022-06-13 22:25 UTC, tjeaneric commented on webpack.dev.js
> +<<<<<<< HEAD
Resolved now.

2022-06-14 04:44 UTC, furebo approved these changes

2022-06-14 04:45 UTC, merged