Ft reset password
atlp-rwanda/Dominators-Phantom-FE pull request #19
Opened 2022-05-02 12:56 UTC by GilbertUp

#What does this PR do?
- It allows users to provide their email to receive password reset links.
- It allows users to reset passwords by entering a new password and confirming it.

##How should this be tested?
-Clone this [repo](https://github.com/atlp-rwanda/Dominators-Phantom-FE/) 
-checkout to the branch name  #ft-reset-password
-Run the command 
-run the command npm i 
-run the command npm start to start a server
-Click on forgot password
-enter your email
-Send link
-To access the password reset form input its  route in the URL field (http://localhost:3000/reset-pwd) this will be accessed after receiving the password reset link in the users email and it will be done by backend-team
## What to expect?
-if the email is in invalid format or missing, an appropriate message will be displayed
-if the password is missing or less than 8 characters, an appropriate message will be displayed
-if the password mismatches and if it does not contain a number, an appropriate message will be displayed

2022-05-02 17:15 UTC, aimelive approved these changes

2022-06-09 13:33 UTC, UmuhireJessie approved these changes

2022-06-12 19:55 UTC, Anguandia commented
Please rebase and squash commits as we review and test locally. This PR is long overdue, treat is as a matter of urgency, @GilbertUp

2022-06-21 08:54 UTC, furebo requested changes
Please Also remember the good description of the PR

2022-06-21 08:54 UTC, furebo commented on src/components/ResetPassword/ResetPassword.css
> +}
Please add the margin auto  to this elements.

2022-06-21 08:54 UTC, furebo commented on src/components/ResetPassword/ResetPwdComponent.js
>      }
Integrate with Backend to reset password before we get the successful message

2022-06-26 09:08 UTC, Anguandia approved these changes
@gerard1001 , I thought this should be ready by now, please note:
- modify the PR description, especially how to test
- I hope we are using real users from the database, not the users.json
- ping @furebo after pushing so he can resolve his change request

2022-06-26 09:08 UTC, Anguandia commented on src/App.js
> +      <Route path="/Reset-pwd" element={<ResetPwd />} />
@gerard1001 remember to change these paths to reset

2022-06-26 09:09 UTC, Anguandia requested changes
Remove any redundant files/pieces of code

2022-06-26 17:27 UTC, Anguandia approved these changes

2022-06-26 19:05 UTC, furebo approved these changes

2022-06-26 19:10 UTC, merged