Ft Logout Function and Update profile
atlp-rwanda/Dominators-Phantom-FE pull request #21
Opened 2022-05-04 12:31 UTC by aimelive

Logout function and update profile page with asynchronous functionality.

2022-05-06 13:57 UTC, GilbertUp approved these changes

2022-05-10 14:54 UTC, UmuhireJessie approved these changes

2022-05-13 10:46 UTC, fab-ryan requested changes
resolve conflicts

2022-06-12 19:42 UTC, Anguandia reviewed
Please resolve conflicts, squash commits, and resolve old conversations for any meaningful review to ensue

2022-06-15 16:23 UTC, Anguandia commented
Hello @aimelive, please exclude logout functionality. It's a different concern that should not be mixed with update-profile. Additionally, it has been implemented
Remember to rebase and squash after

2022-06-26 16:42 UTC, closed without merging