Ft assign drivers to buses
atlp-rwanda/Dominators-Phantom-FE pull request #24
Opened 2022-05-20 12:19 UTC by fab-ryan

### **Feature Assign Drivers to Buses**
The Operator will be able to assign registered drivers to registered buses 
**Acceptance Criteria**

- [ ] The operator should be able to assign a driver to a bus.

- [ ] The operator should be able to view a paginated list of driver to bus assignments.

- [ ] The driver should receive a bus assignment and un-assignment email & in-app notifications.

- [ ] Skeleton UIs/screen are/is shown when the page loads/is loading.

- [ ] Appropriate error messages are displayed on unsuccessful attempts

2022-05-23 14:32 UTC, GilbertUp approved these changes

2022-06-09 13:11 UTC, UmuhireJessie approved these changes

2022-06-09 23:10 UTC, Anguandia requested changes
Great work, please look into the following:
- Please describe how I should test this PR locally (on my laptop)
- I can only see the home and routes pages, is `ft-assign-drivers-to-buses` a misnomer?
- Additionally, please find time to respond to the in-code comments

2022-06-09 23:10 UTC, Anguandia commented on crude-route.json
> +}
We can not yet get this from the backend?

2022-06-09 23:10 UTC, Anguandia commented on src/utils/db.js
> +export const db = "http://localhost:4000";
I think it will offer greater flexibility if we read the backend url from the environment.

2022-06-26 05:00 UTC, furebo requested changes
Please rebase and resolve the conflicts.

2022-06-30 06:47 UTC, furebo approved these changes

2022-06-30 06:47 UTC, merged