Ft login page bug fix
atlp-rwanda/Dominators-Phantom-FE pull request #25
Opened 2022-05-24 09:58 UTC by GilbertUp

### What does this PR do?

It allows registered user to login

### How should this be tested?
-Clone this [repo](https://github.com/atlp-rwanda/Dominators-Phantom-FE/compare/develop...ft-login-page-bug-fix)
-checkout to the branch called ft-login-page-bud-fix
-Run the command npm i and later npm start
-click on login and in put admin7@test.comand pass12345 as user admin  credential
### What to expect?
-if the email is in invalid format or missing, an appropriate message will be displayed
-if the password is missing or less than 8 characters, an appropriate message will be displayed
-For successful attempt you will be redirected to admin dashboard and error messages are displayed for unsuccessful attempts
### Acceptance criteria

- [ ] Appropriate error messages are displayed on invalid inputs (Form validation).
- [ ] Appropriate error messages are displayed on unsuccessful attempts
- [ ]  Upon successful login, the user should be redirected to their notification page (At this point in time, the notification page might be a black page).
- [ ]  Skeleton UIs/screen are/is shown when the page loads/is loading.
- [ ]  The page is responsive
- [ ]  Each user  role upon successful login should be redirected to their respective profile page

2022-05-24 16:15 UTC, aimelive approved these changes

2022-05-25 06:46 UTC, furebo requested changes
Remove the console.log lines and squash the commits to one commit

2022-05-25 06:46 UTC, furebo commented on src/components/Login/LoginComponent.js
> +    console.log(db)
Please remove the console.log line.

2022-05-25 06:46 UTC, furebo commented on src/components/Login/LoginComponent.js
> +      console.log(result)
Please remove also the console.log line

2022-06-09 09:48 UTC, Anguandia commented
Please note the following:

@GilbertUp good PR description. Much as you are now in the backend, please address the following
- squash these commits, 38 is unacceptable
- was this a bug or a feature? the branch name is confusing. Please rename it following the team conventions and best practices documented [here](https://github.com/atlp-rwanda/engineering-playbook/tree/master/5.%20Developing/Conventions#branch-naming)
- despite the spot-on PR description, the formatting is still wanting, please acquaint yourself with markdown syntax. you can search online

@fab-ryan you now own this task, please respond to any technical review comments/change requests to this PR. Also address the following:
- write unit tests for the feature
- test setup is wanting, you may start from setting up testing

2022-06-09 12:53 UTC, UmuhireJessie approved these changes

2022-06-09 21:07 UTC, Anguandia commented
A few more observations:
- please change the cursor to pointer when hovering over the login button
- it will be good to read the backend base url from the environment so that different instances may be used in different environments

2022-06-14 13:50 UTC, furebo requested changes
Hi good work Gelard but resolve the appearing conflicts do the requested change

2022-06-14 13:50 UTC, furebo commented on src/components/Login/LoginComponent.js
> +          }
Please remove the empty else block

2022-06-14 19:33 UTC, Anguandia approved these changes
Good work! just the 2 changes, we'll be good to go

2022-06-14 19:33 UTC, Anguandia commented on src/utils/db.js
> +export const db = "http://localhost:4000/api/v1";
We need to dynamically inject this from the environment

2022-06-14 19:33 UTC, Anguandia commented on package.json
>      "@babel/core": "^7.17.9",
We also need to streamline project vs dev dependencies

2022-06-15 05:10 UTC, furebo approved these changes

2022-06-15 05:10 UTC, merged