Feature in app notification to drivers bus
atlp-rwanda/Dominators-Phantom-FE pull request #33
Opened 2022-06-25 23:31 UTC by fab-ryan

2022-06-26 10:38 UTC, UmuhireJessie requested changes, later dismissed
resolve conflicts

2022-06-26 18:34 UTC, aimelive approved these changes

2022-07-13 18:45 UTC, GilbertUp approved these changes

2022-07-14 10:14 UTC, UmuhireJessie commented
@fab-ryan, please add a description of how to test manually your PR

2022-07-17 06:19 UTC, furebo approved these changes

2022-07-17 11:46 UTC, merged