Ft landing page
atlp-rwanda/Dominators-Phantom-FE pull request #7
Opened 2022-04-13 14:11 UTC by fab-ryan

2022-04-13 15:37 UTC, Anguandia requested changes, later dismissed

2022-04-13 15:37 UTC, Anguandia commented on README.md
> +- make copy of .env.example to .env and make change due to file configuration
Correct the grammer

2022-04-18 08:15 UTC, GilbertUp approved these changes

2022-04-18 10:12 UTC, gerard1001 approved these changes

2022-04-18 13:13 UTC, furebo requested changes
Reduce the number of commits (squash) resolve the conflicts and delete the commented codes  in logout.jsx file

2022-04-18 13:13 UTC, furebo commented on src/style.css
Resolve the conflicts in this file src/style.css

2022-04-18 13:13 UTC, furebo commented on src/pages/Logout.jsx
>  import logout from '../images/logout.png'
Resolve conflicts in this file src/pages/Logout.jsx

2022-04-18 13:35 UTC, furebo approved these changes

2022-04-18 13:37 UTC, merged