Ch setup redux
atlp-rwanda/Dominators-Phantom-FE pull request #9
Opened 2022-04-13 19:07 UTC by UmuhireJessie

2022-04-14 09:28 UTC, fab-ryan approved these changes

2022-04-18 10:14 UTC, gerard1001 approved these changes

2022-04-18 13:25 UTC, furebo reviewed
there is a conflict in App.js file. Please resolve it.

2022-04-21 15:02 UTC, furebo requested changes
Please squash the commit

2022-04-21 19:21 UTC, aimelive approved these changes

2022-04-22 11:01 UTC, furebo approved these changes

2022-04-22 11:01 UTC, merged